using System.Collections;
using System.Collections.Generic;
using wowapi.Enumerations;
using wowapi.Models.Db.Classic;
using wowapi.Models.Search;

namespace wowapi.Extensions
{
    public static class ItemTemplateExtensions
    {
        public static bool IsObjectNull(this CItemTemplate itemTemplate)
        {
            return itemTemplate == null;
        }

        public static bool IsEmptyObject(this CItemTemplate itemTemplate)
        {
            return itemTemplate.Entry == 0;
        }

        public static object CreateResponeObject(this CItemTemplate itemTemplate)
        {
            switch (itemTemplate.Class)
            {
                case (byte)ItemEnums.ItemClasses.CONSUMEABLE:
                    return new
                    {
                        Entry = itemTemplate.Entry,
                        Level = itemTemplate.ItemLevel,
                        Quality = itemTemplate.Quality,
                        BuyPrice = itemTemplate.BuyPrice,
                        BuyCount = itemTemplate.BuyCount,
                        SellPrice = itemTemplate.SellPrice,
                        Name = itemTemplate.Name,
                        Bonding = itemTemplate.Bonding,
                        Flags = itemTemplate.Flags,
                        InventoryType = itemTemplate.InventoryType,
                        Class = itemTemplate.Class,
                        SubClass = itemTemplate.Subclass,
                        AllowableClass = itemTemplate.AllowableClass,
                        AllowableRace = itemTemplate.AllowableRace,
                        Description = itemTemplate.Description,
                        Material = itemTemplate.Material,
                        Stackable = itemTemplate.Stackable,
                        MaxCount = itemTemplate.Maxcount,
                        Duration = itemTemplate.Duration,
                        ReqLevel = itemTemplate.RequiredLevel,
                        ReqSkill = itemTemplate.RequiredSkill,
                        ReqSkillRank = itemTemplate.RequiredSkillRank,
                        FoodType = itemTemplate.FoodType,
                        SpellId1 = itemTemplate.Spellid1,
                        SpellPpmRate1 = itemTemplate.SpellppmRate1,
                        SpellTrigger1 = itemTemplate.Spelltrigger1,
                        SpellCharges1 = itemTemplate.Spellcharges1,
                        SpellCategory1 = itemTemplate.Spellcategory1,
                        SpellCooldown1 = itemTemplate.Spellcooldown1,
                        SpellCategoryCooldown1 = itemTemplate.Spellcategorycooldown1,
                        SpellId2 = itemTemplate.Spellid2,
                        SpellPpmRate2 = itemTemplate.SpellppmRate2,
                        SpellTrigger2 = itemTemplate.Spelltrigger2,
                        SpellCharges2 = itemTemplate.Spellcharges2,
                        SpellCategory2 = itemTemplate.Spellcategory2,
                        SpellCooldown2 = itemTemplate.Spellcooldown2,
                        SpellCategoryCooldown2 = itemTemplate.Spellcategorycooldown2,
                        SpellId3 = itemTemplate.Spellid3,
                        SpellPpmRate3 = itemTemplate.SpellppmRate3,
                        SpellTrigger3 = itemTemplate.Spelltrigger3,
                        SpellCharges3 = itemTemplate.Spellcharges3,
                        SpellCategory3 = itemTemplate.Spellcategory3,
                        SpellCooldown3 = itemTemplate.Spellcooldown3,
                        SpellCategoryCooldown3 = itemTemplate.Spellcategorycooldown3,
                        SpellId4 = itemTemplate.Spellid4,
                        SpellPpmRate4 = itemTemplate.SpellppmRate4,
                        SpellTrigger4 = itemTemplate.Spelltrigger4,
                        SpellCharges4 = itemTemplate.Spellcharges4,
                        SpellCategory4 = itemTemplate.Spellcategory4,
                        SpellCooldown4 = itemTemplate.Spellcooldown4,
                        SpellCategoryCooldown4 = itemTemplate.Spellcategorycooldown4,
                        SpellId5 = itemTemplate.Spellid5,
                        SpellPpmRate5 = itemTemplate.SpellppmRate5,
                        SpellTrigger5 = itemTemplate.Spelltrigger5,
                        SpellCharges5 = itemTemplate.Spellcharges5,
                        SpellCategory5 = itemTemplate.Spellcategory5,
                        SpellCooldown5 = itemTemplate.Spellcooldown5,
                        SpellCategoryCooldown5 = itemTemplate.Spellcategorycooldown5,
                        ItemIcon = itemTemplate.Icon,
                        DroppedBy = itemTemplate.DroppedBy.CreateResultObject(),
                        //SoldBy = ,
                        //ContainedIn =,
                        //RewardFrom = ,
                        //CreatedBy = ,
                    };
                case (byte)ItemEnums.ItemClasses.CONTAINER:
                case (byte)ItemEnums.ItemClasses.QUIVER:
                    return new
                    {
                        Entry = itemTemplate.Entry,
                        Level = itemTemplate.ItemLevel,
                        Quality = itemTemplate.Quality,
                        BuyPrice = itemTemplate.BuyPrice,
                        BuyCount = itemTemplate.BuyCount,
                        SellPrice = itemTemplate.SellPrice,
                        Name = itemTemplate.Name,
                        Bonding = itemTemplate.Bonding,
                        ContainerSlots = itemTemplate.ContainerSlots,
                        Flags = itemTemplate.Flags,
                        InventoryType = itemTemplate.InventoryType,
                        BagFamily = itemTemplate.BagFamily,
                        Class = itemTemplate.Class,
                        SubClass = itemTemplate.Subclass,
                        AllowableClass = itemTemplate.AllowableClass,
                        AllowableRace = itemTemplate.AllowableRace,
                        Description = itemTemplate.Description,
                        Material = itemTemplate.Material,
                        ItemIcon = itemTemplate.Icon,
                        DroppedBy = itemTemplate.DroppedBy.CreateResultObject(),
                        //SoldBy = ,
                        //ContainedIn =,
                        //RewardFrom = ,
                        //CreatedBy = ,
                    };
                case (byte)ItemEnums.ItemClasses.WEAPON:
                    return new
                    {
                        Entry = itemTemplate.Entry,
                        Level = itemTemplate.ItemLevel,
                        Quality = itemTemplate.Quality,
                        BuyPrice = itemTemplate.BuyPrice,
                        BuyCount = itemTemplate.BuyCount,
                        SellPrice = itemTemplate.SellPrice,
                        Name = itemTemplate.Name,
                        Bonding = itemTemplate.Bonding,
                        Flags = itemTemplate.Flags,
                        InventoryType = itemTemplate.InventoryType,
                        Class = itemTemplate.Class,
                        SubClass = itemTemplate.Subclass,
                        MinDmg1 = itemTemplate.DmgMin1,
                        MaxDmg1 = itemTemplate.DmgMax1,
                        MinDmg2 = itemTemplate.DmgMin2,
                        MaxDmg2 = itemTemplate.DmgMax2,
                        Speed = itemTemplate.Delay / 1000.0F,
                        Dps = itemTemplate.CalculateItemDps(),
                        StatType1 = itemTemplate.StatType1,
                        StatValue1 = itemTemplate.StatValue1,
                        StatType2 = itemTemplate.StatType2,
                        StatValue2 = itemTemplate.StatValue2,
                        StatType3 = itemTemplate.StatType3,
                        StatValue3 = itemTemplate.StatValue3,
                        StatType4 = itemTemplate.StatType4,
                        StatValue4 = itemTemplate.StatValue4,
                        StatType5 = itemTemplate.StatType5,
                        StatValue5 = itemTemplate.StatValue5,
                        StatType6 = itemTemplate.StatType6,
                        StatValue6 = itemTemplate.StatValue6,
                        StatType7 = itemTemplate.StatType7,
                        StatValue7 = itemTemplate.StatValue7,
                        StatType8 = itemTemplate.StatType8,
                        StatValue8 = itemTemplate.StatValue8,
                        StatType9 = itemTemplate.StatType9,
                        StatValue9 = itemTemplate.StatValue9,
                        StatType10 = itemTemplate.StatType10,
                        StatValue10 = itemTemplate.StatValue10,
                        Durability = itemTemplate.MaxDurability,
                        ReqLevel = itemTemplate.RequiredLevel,
                        ReqSpell = itemTemplate.Requiredspell,
                        ReqSkill = itemTemplate.RequiredSkill,
                        ReqSkillRank = itemTemplate.RequiredSkillRank,
                        ReqRepFaction = itemTemplate.RequiredReputationFaction,
                        ReqRepFactionRank = itemTemplate.RequiredReputationRank,
                        ReqHonorRank = itemTemplate.Requiredhonorrank,
                        AllowableClass = itemTemplate.AllowableClass,
                        AllowableRace = itemTemplate.AllowableRace,
                        SpellId1 = itemTemplate.Spellid1,
                        SpellPpmRate1 = itemTemplate.SpellppmRate1,
                        SpellTrigger1 = itemTemplate.Spelltrigger1,
                        SpellCharges1 = itemTemplate.Spellcharges1,
                        SpellCategory1 = itemTemplate.Spellcategory1,
                        SpellCooldown1 = itemTemplate.Spellcooldown1,
                        SpellCategoryCooldown1 = itemTemplate.Spellcategorycooldown1,
                        SpellId2 = itemTemplate.Spellid2,
                        SpellPpmRate2 = itemTemplate.SpellppmRate2,
                        SpellTrigger2 = itemTemplate.Spelltrigger2,
                        SpellCharges2 = itemTemplate.Spellcharges2,
                        SpellCategory2 = itemTemplate.Spellcategory2,
                        SpellCooldown2 = itemTemplate.Spellcooldown2,
                        SpellCategoryCooldown2 = itemTemplate.Spellcategorycooldown2,
                        SpellId3 = itemTemplate.Spellid3,
                        SpellPpmRate3 = itemTemplate.SpellppmRate3,
                        SpellTrigger3 = itemTemplate.Spelltrigger3,
                        SpellCharges3 = itemTemplate.Spellcharges3,
                        SpellCategory3 = itemTemplate.Spellcategory3,
                        SpellCooldown3 = itemTemplate.Spellcooldown3,
                        SpellCategoryCooldown3 = itemTemplate.Spellcategorycooldown3,
                        SpellId4 = itemTemplate.Spellid4,
                        SpellPpmRate4 = itemTemplate.SpellppmRate4,
                        SpellTrigger4 = itemTemplate.Spelltrigger4,
                        SpellCharges4 = itemTemplate.Spellcharges4,
                        SpellCategory4 = itemTemplate.Spellcategory4,
                        SpellCooldown4 = itemTemplate.Spellcooldown4,
                        SpellCategoryCooldown4 = itemTemplate.Spellcategorycooldown4,
                        SpellId5 = itemTemplate.Spellid5,
                        SpellPpmRate5 = itemTemplate.SpellppmRate5,
                        SpellTrigger5 = itemTemplate.Spelltrigger5,
                        SpellCharges5 = itemTemplate.Spellcharges5,
                        SpellCategory5 = itemTemplate.Spellcategory5,
                        SpellCooldown5 = itemTemplate.Spellcooldown5,
                        SpellCategoryCooldown5 = itemTemplate.Spellcategorycooldown5,
                        Description = itemTemplate.Description,
                        DisenchantId = itemTemplate.DisenchantId,
                        ItemSetObj = itemTemplate.ItemSetObj != null ? itemTemplate.ItemSetObj.CreateResponeObject() : new object(),
                        ItemIcon = itemTemplate.Icon,
                        DroppedBy = itemTemplate.DroppedBy.CreateResultObject(),
                        //SoldBy = ,
                        //Disenchanting = ,
                        //ContainedIn =,
                        //RewardFrom = ,
                        //CreatedBy = ,
                    };
                case (byte)ItemEnums.ItemClasses.ARMOR:
                    return new
                    {
                        Entry = itemTemplate.Entry,
                        Level = itemTemplate.ItemLevel,
                        Quality = itemTemplate.Quality,
                        BuyPrice = itemTemplate.BuyPrice,
                        BuyCount = itemTemplate.BuyCount,
                        SellPrice = itemTemplate.SellPrice,
                        Name = itemTemplate.Name,
                        Bonding = itemTemplate.Bonding,
                        Flags = itemTemplate.Flags,
                        InventoryType = itemTemplate.InventoryType,
                        Class = itemTemplate.Class,
                        SubClass = itemTemplate.Subclass,
                        StatType1 = itemTemplate.StatType1,
                        StatValue1 = itemTemplate.StatValue1,
                        StatType2 = itemTemplate.StatType2,
                        StatValue2 = itemTemplate.StatValue2,
                        StatType3 = itemTemplate.StatType3,
                        StatValue3 = itemTemplate.StatValue3,
                        StatType4 = itemTemplate.StatType4,
                        StatValue4 = itemTemplate.StatValue4,
                        StatType5 = itemTemplate.StatType5,
                        StatValue5 = itemTemplate.StatValue5,
                        StatType6 = itemTemplate.StatType6,
                        StatValue6 = itemTemplate.StatValue6,
                        StatType7 = itemTemplate.StatType7,
                        StatValue7 = itemTemplate.StatValue7,
                        StatType8 = itemTemplate.StatType8,
                        StatValue8 = itemTemplate.StatValue8,
                        StatType9 = itemTemplate.StatType9,
                        StatValue9 = itemTemplate.StatValue9,
                        StatType10 = itemTemplate.StatType10,
                        StatValue10 = itemTemplate.StatValue10,
                        Durability = itemTemplate.MaxDurability,
                        ReqLevel = itemTemplate.RequiredLevel,
                        ReqSpell = itemTemplate.Requiredspell,
                        ReqSkill = itemTemplate.RequiredSkill,
                        ReqSkillRank = itemTemplate.RequiredSkillRank,
                        ReqRepFaction = itemTemplate.RequiredReputationFaction,
                        ReqRepFactionRank = itemTemplate.RequiredReputationRank,
                        ReqHonorRank = itemTemplate.Requiredhonorrank,
                        AllowableClass = itemTemplate.AllowableClass,
                        AllowableRace = itemTemplate.AllowableRace,
                        SpellId1 = itemTemplate.Spellid1,
                        SpellPpmRate1 = itemTemplate.SpellppmRate1,
                        SpellTrigger1 = itemTemplate.Spelltrigger1,
                        SpellCharges1 = itemTemplate.Spellcharges1,
                        SpellCategory1 = itemTemplate.Spellcategory1,
                        SpellCooldown1 = itemTemplate.Spellcooldown1,
                        SpellCategoryCooldown1 = itemTemplate.Spellcategorycooldown1,
                        SpellId2 = itemTemplate.Spellid2,
                        SpellPpmRate2 = itemTemplate.SpellppmRate2,
                        SpellTrigger2 = itemTemplate.Spelltrigger2,
                        SpellCharges2 = itemTemplate.Spellcharges2,
                        SpellCategory2 = itemTemplate.Spellcategory2,
                        SpellCooldown2 = itemTemplate.Spellcooldown2,
                        SpellCategoryCooldown2 = itemTemplate.Spellcategorycooldown2,
                        SpellId3 = itemTemplate.Spellid3,
                        SpellPpmRate3 = itemTemplate.SpellppmRate3,
                        SpellTrigger3 = itemTemplate.Spelltrigger3,
                        SpellCharges3 = itemTemplate.Spellcharges3,
                        SpellCategory3 = itemTemplate.Spellcategory3,
                        SpellCooldown3 = itemTemplate.Spellcooldown3,
                        SpellCategoryCooldown3 = itemTemplate.Spellcategorycooldown3,
                        SpellId4 = itemTemplate.Spellid4,
                        SpellPpmRate4 = itemTemplate.SpellppmRate4,
                        SpellTrigger4 = itemTemplate.Spelltrigger4,
                        SpellCharges4 = itemTemplate.Spellcharges4,
                        SpellCategory4 = itemTemplate.Spellcategory4,
                        SpellCooldown4 = itemTemplate.Spellcooldown4,
                        SpellCategoryCooldown4 = itemTemplate.Spellcategorycooldown4,
                        SpellId5 = itemTemplate.Spellid5,
                        SpellPpmRate5 = itemTemplate.SpellppmRate5,
                        SpellTrigger5 = itemTemplate.Spelltrigger5,
                        SpellCharges5 = itemTemplate.Spellcharges5,
                        SpellCategory5 = itemTemplate.Spellcategory5,
                        SpellCooldown5 = itemTemplate.Spellcooldown5,
                        SpellCategoryCooldown5 = itemTemplate.Spellcategorycooldown5,
                        Description = itemTemplate.Description,
                        DisenchantId = itemTemplate.DisenchantId,
                        ItemSetObj = itemTemplate.ItemSetObj != null ? itemTemplate.ItemSetObj.CreateResponeObject() : new object(),
                        ItemIcon = itemTemplate.Icon,
                        DroppedBy = itemTemplate.DroppedBy.CreateResultObject(),
                        //SoldBy = ,
                        //Disenchanting = ,
                        //ContainedIn =,
                        //RewardFrom = ,
                        //CreatedBy = ,
                    };
                case (byte)ItemEnums.ItemClasses.REAGENT:
                    return new
                    {
                        Entry = itemTemplate.Entry,
                        Level = itemTemplate.ItemLevel,
                        Quality = itemTemplate.Quality,
                        BuyPrice = itemTemplate.BuyPrice,
                        BuyCount = itemTemplate.BuyCount,
                        SellPrice = itemTemplate.SellPrice,
                        Name = itemTemplate.Name,
                        Bonding = itemTemplate.Bonding,
                        Flags = itemTemplate.Flags,
                        InventoryType = itemTemplate.InventoryType,
                        Class = itemTemplate.Class,
                        SubClass = itemTemplate.Subclass,
                        AllowableClass = itemTemplate.AllowableClass,
                        AllowableRace = itemTemplate.AllowableRace,
                        Description = itemTemplate.Description,
                        Material = itemTemplate.Material,
                        SpellId1 = itemTemplate.Spellid1,
                        SpellPpmRate1 = itemTemplate.SpellppmRate1,
                        SpellTrigger1 = itemTemplate.Spelltrigger1,
                        SpellCharges1 = itemTemplate.Spellcharges1,
                        SpellCategory1 = itemTemplate.Spellcategory1,
                        SpellCooldown1 = itemTemplate.Spellcooldown1,
                        SpellCategoryCooldown1 = itemTemplate.Spellcategorycooldown1,
                        SpellId2 = itemTemplate.Spellid2,
                        SpellPpmRate2 = itemTemplate.SpellppmRate2,
                        SpellTrigger2 = itemTemplate.Spelltrigger2,
                        SpellCharges2 = itemTemplate.Spellcharges2,
                        SpellCategory2 = itemTemplate.Spellcategory2,
                        SpellCooldown2 = itemTemplate.Spellcooldown2,
                        SpellCategoryCooldown2 = itemTemplate.Spellcategorycooldown2,
                        SpellId3 = itemTemplate.Spellid3,
                        SpellPpmRate3 = itemTemplate.SpellppmRate3,
                        SpellTrigger3 = itemTemplate.Spelltrigger3,
                        SpellCharges3 = itemTemplate.Spellcharges3,
                        SpellCategory3 = itemTemplate.Spellcategory3,
                        SpellCooldown3 = itemTemplate.Spellcooldown3,
                        SpellCategoryCooldown3 = itemTemplate.Spellcategorycooldown3,
                        SpellId4 = itemTemplate.Spellid4,
                        SpellPpmRate4 = itemTemplate.SpellppmRate4,
                        SpellTrigger4 = itemTemplate.Spelltrigger4,
                        SpellCharges4 = itemTemplate.Spellcharges4,
                        SpellCategory4 = itemTemplate.Spellcategory4,
                        SpellCooldown4 = itemTemplate.Spellcooldown4,
                        SpellCategoryCooldown4 = itemTemplate.Spellcategorycooldown4,
                        SpellId5 = itemTemplate.Spellid5,
                        SpellPpmRate5 = itemTemplate.SpellppmRate5,
                        SpellTrigger5 = itemTemplate.Spelltrigger5,
                        SpellCharges5 = itemTemplate.Spellcharges5,
                        SpellCategory5 = itemTemplate.Spellcategory5,
                        SpellCooldown5 = itemTemplate.Spellcooldown5,
                        SpellCategoryCooldown5 = itemTemplate.Spellcategorycooldown5,
                        ItemIcon = itemTemplate.Icon,
                        DroppedBy = itemTemplate.DroppedBy.CreateResultObject(),
                        //SoldBy = ,
                        //ContainedIn =,
                        //RewardFrom = ,
                        //CreatedBy = ,
                        //ReagentFor = 
                    };
                case (byte)ItemEnums.ItemClasses.PROJECTILE:
                    return new
                    {
                        Entry = itemTemplate.Entry,
                        Level = itemTemplate.ItemLevel,
                        Quality = itemTemplate.Quality,
                        BuyPrice = itemTemplate.BuyPrice,
                        BuyCount = itemTemplate.BuyCount,
                        SellPrice = itemTemplate.SellPrice,
                        Name = itemTemplate.Name,
                        Bonding = itemTemplate.Bonding,
                        InventoryType = itemTemplate.InventoryType,
                        Class = itemTemplate.Class,
                        SubClass = itemTemplate.Subclass,
                        AllowableClass = itemTemplate.AllowableClass,
                        AllowableRace = itemTemplate.AllowableRace,
                        Description = itemTemplate.Description,
                        Material = itemTemplate.Material,
                        ReqRepFaction = itemTemplate.RequiredReputationFaction,
                        ReqRepFactionRank = itemTemplate.RequiredReputationRank,
                        Stackable = itemTemplate.Stackable,
                        MinDmg1 = itemTemplate.DmgMin1,
                        MaxDmg1 = itemTemplate.DmgMax1,
                        Delay = itemTemplate.Delay,
                        ItemIcon = itemTemplate.Icon,
                        DroppedBy = itemTemplate.DroppedBy.CreateResultObject(),
                        //SoldBy = ,
                        //ContainedIn =,
                        //RewardFrom = ,
                        //CreatedBy = ,
                    };
                case (byte)ItemEnums.ItemClasses.TRADE_GOODS:
                    return new
                    {
                        Entry = itemTemplate.Entry,
                        Level = itemTemplate.ItemLevel,
                        Quality = itemTemplate.Quality,
                        BuyPrice = itemTemplate.BuyPrice,
                        BuyCount = itemTemplate.BuyCount,
                        SellPrice = itemTemplate.SellPrice,
                        Name = itemTemplate.Name,
                        Bonding = itemTemplate.Bonding,
                        InventoryType = itemTemplate.InventoryType,
                        Class = itemTemplate.Class,
                        SubClass = itemTemplate.Subclass,
                        AllowableClass = itemTemplate.AllowableClass,
                        AllowableRace = itemTemplate.AllowableRace,
                        Description = itemTemplate.Description,
                        Material = itemTemplate.Material,
                        Stackable = itemTemplate.Stackable,
                        ReqSkill = itemTemplate.RequiredSkill,
                        ReqSkillRank = itemTemplate.RequiredSkillRank,
                        MaxCount = itemTemplate.Maxcount,
                        MinDmg1 = itemTemplate.DmgMin1,
                        MaxDmg1 = itemTemplate.DmgMax1,
                        Delay = itemTemplate.Delay,
                        FoodType = itemTemplate.FoodType,
                        SpellId1 = itemTemplate.Spellid1,
                        SpellPpmRate1 = itemTemplate.SpellppmRate1,
                        SpellTrigger1 = itemTemplate.Spelltrigger1,
                        SpellCharges1 = itemTemplate.Spellcharges1,
                        SpellCategory1 = itemTemplate.Spellcategory1,
                        SpellCooldown1 = itemTemplate.Spellcooldown1,
                        SpellCategoryCooldown1 = itemTemplate.Spellcategorycooldown1,
                        SpellId2 = itemTemplate.Spellid2,
                        SpellPpmRate2 = itemTemplate.SpellppmRate2,
                        SpellTrigger2 = itemTemplate.Spelltrigger2,
                        SpellCharges2 = itemTemplate.Spellcharges2,
                        SpellCategory2 = itemTemplate.Spellcategory2,
                        SpellCooldown2 = itemTemplate.Spellcooldown2,
                        SpellCategoryCooldown2 = itemTemplate.Spellcategorycooldown2,
                        SpellId3 = itemTemplate.Spellid3,
                        SpellPpmRate3 = itemTemplate.SpellppmRate3,
                        SpellTrigger3 = itemTemplate.Spelltrigger3,
                        SpellCharges3 = itemTemplate.Spellcharges3,
                        SpellCategory3 = itemTemplate.Spellcategory3,
                        SpellCooldown3 = itemTemplate.Spellcooldown3,
                        SpellCategoryCooldown3 = itemTemplate.Spellcategorycooldown3,
                        SpellId4 = itemTemplate.Spellid4,
                        SpellPpmRate4 = itemTemplate.SpellppmRate4,
                        SpellTrigger4 = itemTemplate.Spelltrigger4,
                        SpellCharges4 = itemTemplate.Spellcharges4,
                        SpellCategory4 = itemTemplate.Spellcategory4,
                        SpellCooldown4 = itemTemplate.Spellcooldown4,
                        SpellCategoryCooldown4 = itemTemplate.Spellcategorycooldown4,
                        SpellId5 = itemTemplate.Spellid5,
                        SpellPpmRate5 = itemTemplate.SpellppmRate5,
                        SpellTrigger5 = itemTemplate.Spelltrigger5,
                        SpellCharges5 = itemTemplate.Spellcharges5,
                        SpellCategory5 = itemTemplate.Spellcategory5,
                        SpellCooldown5 = itemTemplate.Spellcooldown5,
                        SpellCategoryCooldown5 = itemTemplate.Spellcategorycooldown5,
                        ItemIcon = itemTemplate.Icon,
                        DroppedBy = itemTemplate.DroppedBy.CreateResultObject(),
                        //SoldBy = ,
                        //ContainedIn =,
                        //RewardFrom = ,
                        //CreatedBy = ,
                    };
                case (byte)ItemEnums.ItemClasses.RECIPE:
                    return new
                    {
                        Entry = itemTemplate.Entry,
                        Level = itemTemplate.ItemLevel,
                        Quality = itemTemplate.Quality,
                        BuyPrice = itemTemplate.BuyPrice,
                        BuyCount = itemTemplate.BuyCount,
                        SellPrice = itemTemplate.SellPrice,
                        Name = itemTemplate.Name,
                        Bonding = itemTemplate.Bonding,
                        InventoryType = itemTemplate.InventoryType,
                        Class = itemTemplate.Class,
                        SubClass = itemTemplate.Subclass,
                        AllowableClass = itemTemplate.AllowableClass,
                        AllowableRace = itemTemplate.AllowableRace,
                        Description = itemTemplate.Description,
                        Material = itemTemplate.Material,
                        Stackable = itemTemplate.Stackable,
                        ReqSkill = itemTemplate.RequiredSkill,
                        ReqSkillRank = itemTemplate.RequiredSkillRank,
                        ReqSpell = itemTemplate.Requiredspell,
                        ReqRepFaction = itemTemplate.RequiredReputationFaction,
                        ReqRepFactionRank = itemTemplate.RequiredReputationRank,
                        MaxCount = itemTemplate.Maxcount,
                        SpellId1 = itemTemplate.Spellid1,
                        SpellPpmRate1 = itemTemplate.SpellppmRate1,
                        SpellTrigger1 = itemTemplate.Spelltrigger1,
                        SpellCharges1 = itemTemplate.Spellcharges1,
                        SpellCategory1 = itemTemplate.Spellcategory1,
                        SpellCooldown1 = itemTemplate.Spellcooldown1,
                        SpellCategoryCooldown1 = itemTemplate.Spellcategorycooldown1,
                        SpellId2 = itemTemplate.Spellid2,
                        SpellPpmRate2 = itemTemplate.SpellppmRate2,
                        SpellTrigger2 = itemTemplate.Spelltrigger2,
                        SpellCharges2 = itemTemplate.Spellcharges2,
                        SpellCategory2 = itemTemplate.Spellcategory2,
                        SpellCooldown2 = itemTemplate.Spellcooldown2,
                        SpellCategoryCooldown2 = itemTemplate.Spellcategorycooldown2,
                        SpellId3 = itemTemplate.Spellid3,
                        SpellPpmRate3 = itemTemplate.SpellppmRate3,
                        SpellTrigger3 = itemTemplate.Spelltrigger3,
                        SpellCharges3 = itemTemplate.Spellcharges3,
                        SpellCategory3 = itemTemplate.Spellcategory3,
                        SpellCooldown3 = itemTemplate.Spellcooldown3,
                        SpellCategoryCooldown3 = itemTemplate.Spellcategorycooldown3,
                        SpellId4 = itemTemplate.Spellid4,
                        SpellPpmRate4 = itemTemplate.SpellppmRate4,
                        SpellTrigger4 = itemTemplate.Spelltrigger4,
                        SpellCharges4 = itemTemplate.Spellcharges4,
                        SpellCategory4 = itemTemplate.Spellcategory4,
                        SpellCooldown4 = itemTemplate.Spellcooldown4,
                        SpellCategoryCooldown4 = itemTemplate.Spellcategorycooldown4,
                        SpellId5 = itemTemplate.Spellid5,
                        SpellPpmRate5 = itemTemplate.SpellppmRate5,
                        SpellTrigger5 = itemTemplate.Spelltrigger5,
                        SpellCharges5 = itemTemplate.Spellcharges5,
                        SpellCategory5 = itemTemplate.Spellcategory5,
                        SpellCooldown5 = itemTemplate.Spellcooldown5,
                        SpellCategoryCooldown5 = itemTemplate.Spellcategorycooldown5,
                        PageMaterial = itemTemplate.PageMaterial,
                        PageText = itemTemplate.PageText,
                        ItemIcon = itemTemplate.Icon,
                        DroppedBy = itemTemplate.DroppedBy.CreateResultObject(),
                        //SoldBy = ,
                        //ContainedIn =,
                        //RewardFrom = ,
                        //CreatedBy = ,
                    };
                case (byte)ItemEnums.ItemClasses.KEY:
                    return new
                    {
                        Entry = itemTemplate.Entry,
                        Level = itemTemplate.ItemLevel,
                        Quality = itemTemplate.Quality,
                        BuyPrice = itemTemplate.BuyPrice,
                        BuyCount = itemTemplate.BuyCount,
                        SellPrice = itemTemplate.SellPrice,
                        Name = itemTemplate.Name,
                        Bonding = itemTemplate.Bonding,
                        ContainerSlots = itemTemplate.ContainerSlots,
                        Flags = itemTemplate.Flags,
                        Class = itemTemplate.Class,
                        SubClass = itemTemplate.Subclass,
                        AllowableClass = itemTemplate.AllowableClass,
                        AllowableRace = itemTemplate.AllowableRace,
                        Description = itemTemplate.Description,
                        Stackable = itemTemplate.Stackable,
                        MaxCount = itemTemplate.Maxcount,
                        SpellId1 = itemTemplate.Spellid1,
                        SpellPpmRate1 = itemTemplate.SpellppmRate1,
                        SpellTrigger1 = itemTemplate.Spelltrigger1,
                        SpellCharges1 = itemTemplate.Spellcharges1,
                        SpellCategory1 = itemTemplate.Spellcategory1,
                        SpellCooldown1 = itemTemplate.Spellcooldown1,
                        SpellCategoryCooldown1 = itemTemplate.Spellcategorycooldown1,
                        SpellId2 = itemTemplate.Spellid2,
                        SpellPpmRate2 = itemTemplate.SpellppmRate2,
                        SpellTrigger2 = itemTemplate.Spelltrigger2,
                        SpellCharges2 = itemTemplate.Spellcharges2,
                        SpellCategory2 = itemTemplate.Spellcategory2,
                        SpellCooldown2 = itemTemplate.Spellcooldown2,
                        SpellCategoryCooldown2 = itemTemplate.Spellcategorycooldown2,
                        SpellId3 = itemTemplate.Spellid3,
                        SpellPpmRate3 = itemTemplate.SpellppmRate3,
                        SpellTrigger3 = itemTemplate.Spelltrigger3,
                        SpellCharges3 = itemTemplate.Spellcharges3,
                        SpellCategory3 = itemTemplate.Spellcategory3,
                        SpellCooldown3 = itemTemplate.Spellcooldown3,
                        SpellCategoryCooldown3 = itemTemplate.Spellcategorycooldown3,
                        SpellId4 = itemTemplate.Spellid4,
                        SpellPpmRate4 = itemTemplate.SpellppmRate4,
                        SpellTrigger4 = itemTemplate.Spelltrigger4,
                        SpellCharges4 = itemTemplate.Spellcharges4,
                        SpellCategory4 = itemTemplate.Spellcategory4,
                        SpellCooldown4 = itemTemplate.Spellcooldown4,
                        SpellCategoryCooldown4 = itemTemplate.Spellcategorycooldown4,
                        SpellId5 = itemTemplate.Spellid5,
                        SpellPpmRate5 = itemTemplate.SpellppmRate5,
                        SpellTrigger5 = itemTemplate.Spelltrigger5,
                        SpellCharges5 = itemTemplate.Spellcharges5,
                        SpellCategory5 = itemTemplate.Spellcategory5,
                        SpellCooldown5 = itemTemplate.Spellcooldown5,
                        SpellCategoryCooldown5 = itemTemplate.Spellcategorycooldown5,
                        ItemIcon = itemTemplate.Icon,
                        DroppedBy = itemTemplate.DroppedBy.CreateResultObject(),
                        //SoldBy = ,
                        //ContainedIn =,
                        //RewardFrom = ,
                        //CreatedBy = ,
                    };
                case (byte)ItemEnums.ItemClasses.MISC:
                    return new
                    {
                        Entry = itemTemplate.Entry,
                        Level = itemTemplate.ItemLevel,
                        Quality = itemTemplate.Quality,
                        BuyPrice = itemTemplate.BuyPrice,
                        BuyCount = itemTemplate.BuyCount,
                        SellPrice = itemTemplate.SellPrice,
                        Name = itemTemplate.Name,
                        Bonding = itemTemplate.Bonding,
                        ContainerSlots = itemTemplate.ContainerSlots,
                        Flags = itemTemplate.Flags,
                        Class = itemTemplate.Class,
                        SubClass = itemTemplate.Subclass,
                        AllowableClass = itemTemplate.AllowableClass,
                        AllowableRace = itemTemplate.AllowableRace,
                        Description = itemTemplate.Description,
                        Stackable = itemTemplate.Stackable,
                        MaxCount = itemTemplate.Maxcount,
                        ReqSkill = itemTemplate.RequiredSkill,
                        ReqSkillRank = itemTemplate.RequiredSkillRank,
                        StartQuest = itemTemplate.Startquest,
                        MinMoneyLoot = itemTemplate.MinMoneyLoot,
                        MaxMoneyLoot = itemTemplate.MaxMoneyLoot,
                        SpellId1 = itemTemplate.Spellid1,
                        SpellPpmRate1 = itemTemplate.SpellppmRate1,
                        SpellTrigger1 = itemTemplate.Spelltrigger1,
                        SpellCharges1 = itemTemplate.Spellcharges1,
                        SpellCategory1 = itemTemplate.Spellcategory1,
                        SpellCooldown1 = itemTemplate.Spellcooldown1,
                        SpellCategoryCooldown1 = itemTemplate.Spellcategorycooldown1,
                        SpellId2 = itemTemplate.Spellid2,
                        SpellPpmRate2 = itemTemplate.SpellppmRate2,
                        SpellTrigger2 = itemTemplate.Spelltrigger2,
                        SpellCharges2 = itemTemplate.Spellcharges2,
                        SpellCategory2 = itemTemplate.Spellcategory2,
                        SpellCooldown2 = itemTemplate.Spellcooldown2,
                        SpellCategoryCooldown2 = itemTemplate.Spellcategorycooldown2,
                        SpellId3 = itemTemplate.Spellid3,
                        SpellPpmRate3 = itemTemplate.SpellppmRate3,
                        SpellTrigger3 = itemTemplate.Spelltrigger3,
                        SpellCharges3 = itemTemplate.Spellcharges3,
                        SpellCategory3 = itemTemplate.Spellcategory3,
                        SpellCooldown3 = itemTemplate.Spellcooldown3,
                        SpellCategoryCooldown3 = itemTemplate.Spellcategorycooldown3,
                        SpellId4 = itemTemplate.Spellid4,
                        SpellPpmRate4 = itemTemplate.SpellppmRate4,
                        SpellTrigger4 = itemTemplate.Spelltrigger4,
                        SpellCharges4 = itemTemplate.Spellcharges4,
                        SpellCategory4 = itemTemplate.Spellcategory4,
                        SpellCooldown4 = itemTemplate.Spellcooldown4,
                        SpellCategoryCooldown4 = itemTemplate.Spellcategorycooldown4,
                        SpellId5 = itemTemplate.Spellid5,
                        SpellPpmRate5 = itemTemplate.SpellppmRate5,
                        SpellTrigger5 = itemTemplate.Spelltrigger5,
                        SpellCharges5 = itemTemplate.Spellcharges5,
                        SpellCategory5 = itemTemplate.Spellcategory5,
                        SpellCooldown5 = itemTemplate.Spellcooldown5,
                        SpellCategoryCooldown5 = itemTemplate.Spellcategorycooldown5,
                        ItemIcon = itemTemplate.Icon,
                        DroppedBy = itemTemplate.DroppedBy.CreateResultObject(),
                        //SoldBy = ,
                        //ContainedIn =,
                        //RewardFrom = ,
                        //CreatedBy = ,
                    };
                default:
                    return new object();
            }
        }
    }
}